Add Protected Species Landing Page
sharkipedia/sharkipedia pull request #730
Opened 2022-11-25 18:39 UTC by redrambles

We have added a Protected Species landing page, which shows all species that have a protected status (CITES, CMS).

The status has a tooltip, we would need the actual help text here.

![image](https://user-images.githubusercontent.com/4411121/204040281-fd7a8fab-f419-4319-9581-e542c9076425.png)

The CITES and CMS statuses can be added to Species in the Admin dashboard.

![image](https://user-images.githubusercontent.com/4411121/204040292-badc7533-36a8-4df0-8765-8d4969be12f2.png)

2022-11-29 13:41 UTC, coffeejunk requested changes

2022-11-29 13:41 UTC, coffeejunk commented on app/controllers/protected_species_controller.rb
> +class ProtectedSpeciesController < ApplicationController
```suggestion
class ProtectedSpeciesController < PreAuthController
```

2022-12-17 15:18 UTC, coffeejunk commented
@creeas any thoughts? 🙂

2022-12-22 02:02 UTC, coffeejunk commented on Gemfile.lock
> +  aws-sdk-s3 (~> 1.114)
```suggestion
  aws-sdk-s3 (~> 1.117)
```

2022-12-22 02:04 UTC, coffeejunk commented on app/javascript/styles.scss
> +@import "@fortawesome/fontawesome-free/scss/fontawesome";
I dropped bulma & fontawesome from the pack, can you load this from via [CDN](https://cdnjs.com/libraries/bulma-tooltip)?

2022-12-22 02:10 UTC, coffeejunk commented on Gemfile.lock
> +    after_commit_everywhere (1.2.2)
```suggestion
    after_commit_everywhere (1.3.0)
```

2022-12-22 02:11 UTC, coffeejunk commented on package.json
> +    "@fortawesome/fontawesome-free": "^6.2.0",
```suggestion
```

load via CDN as mentioned above

2022-12-22 02:11 UTC, coffeejunk commented on yarn.lock
> +
```suggestion
```

2023-01-09 16:18 UTC, creeas commented
> @creeas any thoughts? 🙂

Hey @coffeejunk and @redrambles this looks really great. I like the easy edit in the admin dashboard as well which will make it easier to edit in the future. I will generate some text for each appendix for CITES and CMS and get them to you.

2023-02-13 16:50 UTC, coffeejunk commented
note to self & @redrambles: #828

2023-03-18 21:29 UTC, coffeejunk approved these changes

2023-03-18 21:32 UTC, merged