References entry
sharkipedia/sharkipedia pull request #907
Opened 2023-05-06 17:26 UTC by redrambles

Here's what we have so far! 🦈

2023-06-18 12:01 UTC, coffeejunk requested changes
Yay, thanks for adding the specs!

2023-06-18 12:01 UTC, coffeejunk commented on spec/system/new_reference_form_system_spec.rb
> +  let(:knownAuthor) { create(:author, name: "Known Author") }
This is Ruby 😛
```suggestion
  let(:known_author) { create(:author, name: "Known Author") }
```

2023-06-18 12:01 UTC, coffeejunk commented on spec/system/new_reference_form_system_spec.rb
> +    fill_in "reference_authors_attributes_0_name", with: knownAuthor.name
```suggestion
    fill_in "reference_authors_attributes_0_name", with: known_author.name[0..4]
```

We want the dropdown to show up if only a part of the name is entered.

2023-06-18 12:01 UTC, coffeejunk commented on spec/system/new_reference_form_system_spec.rb
> +    expect(page).to have_selector(".dropdown-item", text: knownAuthor.name)
```suggestion
    expect(page).to have_selector(".dropdown-item", text: known_author.name)
```

2023-06-18 12:01 UTC, coffeejunk commented on spec/system/new_reference_form_system_spec.rb
> +    expect(page).to have_content(knownAuthor.name)
```suggestion
    expect(page).to have_content(known_author.name)
```

2023-06-18 17:59 UTC, redrambles commented on spec/system/new_reference_form_system_spec.rb
> +  let(:knownAuthor) { create(:author, name: "Known Author") }
![tenor-107694682](https://github.com/sharkipedia/sharkipedia/assets/4411121/fa778b58-d1c8-4694-8128-5695d9c7f858)

2023-06-18 21:39 UTC, redrambles commented on spec/system/new_reference_form_system_spec.rb
> +    fill_in "reference_authors_attributes_0_name", with: knownAuthor.name
Ok - also added another step to click on the dropdown, so that the full name is populated - which made it so that the test passed.

2023-06-19 15:14 UTC, coffeejunk reviewed
👏

2023-06-25 13:06 UTC, coffeejunk requested changes
Nice! Needs a tiny fix and then we can merge this 🎉

2023-06-25 13:06 UTC, coffeejunk commented on app/controllers/admin/references_controller.rb
> +
```suggestion
```

2023-06-25 15:33 UTC, coffeejunk approved these changes

2023-06-25 15:34 UTC, merged